# Generated by Django 4.0.1 on 2022-01-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0003_alter_hook_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pattern_code', models.CharField(default='no code', max_length=20)),
                ('instructions', models.TextField()),
                ('notes', models.TextField()),
                ('stitch_image', models.ImageField(upload_to='stitches')),
                ('related_stitches', models.ManyToManyField(null=True, related_name='stitch', to='crochet.Stitch')),
            ],
        ),
    ]
