# Generated by Django 4.0.1 on 2022-01-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0004_stitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stitch',
            name='related_stitches',
            field=models.ManyToManyField(blank=True, null=True, related_name='stitch', to='crochet.Stitch'),
        ),
    ]
