# Generated by Django 4.0.1 on 2022-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0005_alter_stitch_related_stitches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='This is how your yarn will be referenced around the site! Could be the brand or something you associate with the yarn, like "Chunky Wool Yarn".', max_length=100)),
                ('weight', models.IntegerField(choices=[(0, '0 - Lace'), (1, '1 - Superfine'), (2, '2 - Fine'), (3, '3 - Light'), (4, '4 - Medium'), (5, '5 - Bulky'), (6, '6 - Super Bulky'), (7, '7 - Jumbo')], max_length=100)),
                ('weight_description', models.CharField(blank=True, help_text='please include any simple specifcs you would like here. For instance, weight choice <em>3 - Light</em> might include "DK, light worsted" here.', max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(default='No notes.')),
                ('yarn_image', models.TextField(default='https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/yarn-ball-karl-addison.jpg', help_text='this should be a link that leads to the image alone. To get this, find an image you like on the internet, then right click and select "Open Image in New Tab". Go to the newly opened tab and copy the full address from the browser address bar, then paste it here!')),
                ('suggested_hooks', models.ManyToManyField(blank=True, null=True, related_name='yarns', to='crochet.Hook')),
            ],
        ),
    ]
