# Generated by Django 4.0.1 on 2022-01-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0006_yarn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number_of_stitches', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField()),
                ('gauge_image', models.ImageField(upload_to='gauges')),
                ('hook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hooks', to='crochet.hook')),
                ('stitch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stitches', to='crochet.stitch')),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gauges', to='crochet.yarn')),
            ],
        ),
    ]
